name: React Project Build and Deployment

on:
  #push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run CI (with additional environment variables)
      - name: Run CI
        run: npm run ci

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          npm test || echo "FAILURE_FLAG=true" >> $GITHUB_ENV
        env:
          CI: true  # Ensures Jest (or any test framework) runs in CI mode

      # Step 6: Build the React App
      - name: Build React App
        run: |
          npm run build || echo "FAILURE_FLAG=true" >> $GITHUB_ENV

      # Step 7: Log project structure (Success or Failure)
      - name: Log Project Structure
        run: tree -a > project_structure.log

      # Step 8: Archive Logs and Artifacts
      - name: Archive Logs and Artifacts
        run: |
          mkdir -p logs
          cp project_structure.log logs/
          cp -r build logs/build || true
        env:
          FAILURE_FLAG: ${{ env.FAILURE_FLAG }}

      # Step 9: Upload Logs as Artifacts
      - name: Upload Logs as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/

      # Step 10: Upload Logs to S3
      - name: Upload Logs to S3
        if: always()  # Run even if previous steps fail
        run: |
          aws s3 cp logs/ s3://${{ secrets.S3_BUCKET_NAME }}/logs/ --recursive

      # Step 11: Send SNS Notification
      - name: Send SNS Notification
        if: always()
        run: |
          if [[ "${{ env.FAILURE_FLAG }}" == "true" ]]; then
            SUBJECT="React Workflow Status - Failure"
            BODY="The workflow failed. Check logs for details. View run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          else
            SUBJECT="React Workflow Status - Success"
            BODY="The workflow succeeded. Check logs for details. View run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi

          aws sns publish \
            --topic-arn arn:aws:sns:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:${{ secrets.SNS_TOPIC_NAME }} \
            --message "$BODY" \
            --subject "$SUBJECT"

      # Step 12: Fail Workflow if Needed
      - name: Fail Workflow if Any Step Failed
        if: ${{ env.FAILURE_FLAG == 'true' }}
        run: exit 1
