name: Terraform Workflow with EC2 Deployment and Logs Upload to S3 
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to access repository contents

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 3: Configure AWS Credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform_validate.log
        run: |
          terraform validate || echo "FAILURE_FLAG=true" >> $GITHUB_ENV
          true

      # Step 6: Terraform Plan
      - name: Terraform Plan
        env:
          TF_LOG: INFO
          TF_LOG_PATH: terraform_plan.log
        run: |
          terraform plan -out=tfplan || echo "FAILURE_FLAG=true" >> $GITHUB_ENV
          true

      # Step 7: Terraform Apply
      - name: Terraform Apply
        env:
          TF_LOG: TRACE
          TF_LOG_PATH: terraform_apply.log
        run: |
          terraform apply -auto-approve tfplan || echo "FAILURE_FLAG=true" >> $GITHUB_ENV
          true

      # Step 8: Retrieve EC2 Public IP
      - name: Retrieve EC2 Public IP
        id: ec2_output
        run: |
          EC2_PUBLIC_IP=$(terraform output -raw ec2_instance_public_ip)
          echo "EC2_PUBLIC_IP=${EC2_PUBLIC_IP}" >> $GITHUB_ENV

      # Step 9: Display EC2 Public IP
      - name: Display EC2 Public IP
        run: |
          echo "Your application is deployed at: http://${{ env.EC2_PUBLIC_IP }}"

      # Step 10: Ensure Logs Directory Exists
      - name: Ensure Logs Directory Exists
        run: mkdir -p $GITHUB_WORKSPACE/logs


      # Step 11: Copy Logs to Logs Directory
      - name: Copy Logs to Logs Directory
        run: |
          cp terraform_validate.log $GITHUB_WORKSPACE/logs/ || true
          cp terraform_plan.log $GITHUB_WORKSPACE/logs/ || true
          cp terraform_apply.log $GITHUB_WORKSPACE/logs/ || true
          echo "Files in logs directory:"
          ls -alh $GITHUB_WORKSPACE/logs/

      # Step 12: Upload Terraform Logs as Artifacts
      - name: Upload Terraform Logs as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: logs/
      # Step 13: Upload Logs to S3
      - name: Upload Logs to S3
        if: always()  # Ensure this runs even if the workflow fails
        run: |
          aws s3 cp $GITHUB_WORKSPACE/logs/ s3://${{ secrets.S3_BUCKET_NAME }}/logs/ --recursive


      # Step 14: Generate Workflow Run Link
      - name: Generate Workflow Run Link
        id: generate_link
        run: echo "run_url=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_ENV

      # Step 15: Send SNS Notification
      - name: Send SNS Notification
        if: always()
        run: |
          if [[ "${{ env.FAILURE_FLAG }}" == "true" ]]; then
            SUBJECT="Terraform Workflow Status - failure"
            BODY="The Terraform workflow has failed. Please check the logs for details. View the workflow run here: ${{ env.run_url }}"
          else
            SUBJECT="Terraform Workflow Status - success"
            BODY="The Terraform workflow has completed successfully. View your application at: http://${{ env.EC2_PUBLIC_IP }}"
          fi

          aws sns publish \
            --topic-arn arn:aws:sns:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:${{ secrets.SNS_TOPIC_NAME }} \
            --message "$BODY" \
            --subject "$SUBJECT"

      # Step 16: Force Workflow Failure if Any Step Failed
      - name: Fail Workflow if Any Step Failed
        if: ${{ env.FAILURE_FLAG == 'true' }}
        run: |
          echo "One or more Terraform steps failed. Marking workflow as failed."
          exit 1
